### ISSUE TITLE
自动识别

### ISSUE THREAD

**Issue by ldqmaybe** [wenchaosong/OCR_identify#1]
大佬，你这个身份证自动识别（不用点击拍照）是怎么实现的？我想把银行卡的实现了

**Comment by wenchaosong** [comment]
@ldqmaybe  你好,实现的话是根据 百度文字识别 封装的,很高兴的告诉你,银行卡也是可以的

**Comment by wenchaosong** [comment]
@ldqmaybe  鉴于目前文字识别的比较少,我可能近期会加入银行卡和名片的识别哦,到时可以直接调用,不过如果你的项目需求比较紧,可以自己实现
以下是链接 
http://ai.baidu.com/tech/ocr/cards

**Comment by xiaomsh** [comment]
@ldqmaybe  银行卡识别已经加入,具体请参考 demo

**Comment by ldqmaybe** [comment]
@wenchaosong 大佬，我表达的可能不是很清楚。我想要的是像识别身份证那样不用点击拍照

**Comment by xiaomsh** [comment]
@ldqmaybe  有2种方式识别,一个是拍照识别,一个是拍好的图片识别,在拍照页面左下方有个按钮,点击可以选择要识别的图片,你可以仔细看看,或者你把我的项目 clone 下来,运行一下看,很快就清楚了,有问题可以再问我

**Comment by ldqmaybe** [comment]
@wenchaosong 我知道你的意思，代码我也看懂了。但是呢，除了拍照识别和选择本地照片识别之外，我还想要一个  扫描就可以直接识别了（就像身份证正面和反面的识别一样），我看到项目里好像用到了ocr-native-interface.jar，里面好像只是针对身份证的，请大佬解惑

**Comment by xiaomsh** [comment]
@ldqmaybe  你的意思是说跟微信扫描二维码一样是吧,每个项目需求都不一样,不可能我全部写出来,这样我告诉你我的思路,扫描还是扫描的界面,但是多加个定时器,到了多长时间自动触发识别,识别成功后自动跳转到需要的页面并把数据带过去,这样就不用点击拍照,需要注意的是触发识别要判断网络,希望以上能帮到你

**Comment by ldqmaybe** [comment]
@wenchaosong 好的，谢谢大佬！
