### ISSUE TITLE
您好,我这里遇到一个关于释放资源的问题

### ISSUE THREAD

**Issue by hardgit** [wenchaosong/OCR_identify#10]
当我反复进入和退出同一个OCR页面时会出现会出现OCR空对象的引用.
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.baidu.ocr.sdk.utils.CrashReporterHandler.release()' on a null object reference
        at com.baidu.ocr.sdk.OCR.release(OCR.java:863)
这个是在OnDestroy界面时调用的.但是因为快速的进入和退出导致这个空指针.
请问有什么可以判断这个OCR对象不为空时再进行OCR.getInstance(this).release();的方法吗?
随时等待回复!

**Comment by xiaomsh** [comment]
@hardgit  我反复试了很多次，都没有出现这样的情况，是必现的吗？如果是，说下怎么必现的

**Comment by hardgit** [comment]
例如:有一个OneActivity 和 TwoActivity 然后再Two页面的onCreate()里面初始化OCR,在OnDestroy里面释放资源OCR.getInstance(this).release(),再写一个销毁本activity的按钮;
然后点击One页面的某个按钮跳转Two页面.再点击Two页面的销毁页面的按钮返回One页面
如此快速重复会引起我上诉问题.您可以尝试一下

**Comment by xiaomsh** [comment]
@hardgit  我复现了，但是有个前提，所以我想问下，你出现这样的情况是在 demo 里还是实际项目中

**Comment by hardgit** [comment]
项目中的,我暂时找到了一个临时的解决方案,就是定义了一个变量默认为0,当它初始化话时为1,那么在OnDestroy时判断如果等于1就OCR.getInstance(this).release();

**Comment by xiaomsh** [comment]
@hardgit  我复现的情况是出现 2 个界面，关闭后就出现这个问题，根本原因是出现了 2 个识别界面，如果有且只有一个界面是没有出现这个问题的

**Comment by hardgit** [comment]
嗯,有可能,现在的Vivo和华为手机我试过,快速点击两次会连续跳转两个页面,例如:打开Vivo设置页面随便找一个列表item快速点击两次也都会跳转两次.我试过规避用户多次点击的情况,但是效果不理想,您有更好方案吗?

**Comment by xiaomsh** [comment]
@hardgit  首先根本原因是源码没有处理空指针，然后自己这边的处理，首先肯定要防止快速点击，我目前用的是 rxbinding          compile 'com.jakewharton.rxbinding2:rxbinding:2.1.1'      
```
public static void fastClick(final View target, final View.OnClickListener listener) {
        RxView.clicks(target)
                .throttleFirst(1, TimeUnit.SECONDS)
                .subscribe(new Consumer<Object>() {
                    @Override
                    public void accept(Object object) {
                        listener.onClick(target);
                    }
                });
    }

CommenUtil.fastClick(findViewById(R.id.bt_next), new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(MainActivity.this, NextActivity.class);
                startActivity(intent);
            }
        });
```
其次，
```
@Override
    protected void onDestroy() {
        CameraNativeHelper.release();
        // 释放内存资源
        OCR.getInstance(this).init(this);
        OCR.getInstance(this).release();
        super.onDestroy();
    }
```

**Comment by hardgit** [comment]
好吧,感谢您的回复!
