### ISSUE TITLE
有个小需求，证件识别完想要把识别的证件照片和文字一起显示出来。

### ISSUE THREAD

**Issue by shineqstm** [wenchaosong/OCR_identify#5]
在fileUtils里有个getSaveFile方法，是咱们传入的需要保存的文件路径，可是这个做的是个临时存储，会出现，当咱们2次同时调用拍照识别的时候，拿到的文件还是前一个（路径是一样的，但是ocr_ui里并不会覆盖原文件存储来替换前面那张），在不改OCR_UI里文件存储的情况下，有木有更好的办法

**Comment by xiaomsh** [comment]
这个要修改依赖库的，目前暴露出的 api 没有这个功能。
要修改的话比较简单，拍照回调和选择图片回调里处理一下就行了

**Comment by shineqstm** [comment]
这个问题，我前面说的有误，图片保存是会覆盖相同文件的，造成我说的原因是，我用的glide加载图片，由于图片的文件名和路径都是一致的，glide会优先加载自己缓存里相应文件路径下的缓存图片，这样虽然识别的是不同的文件，但glide显示的就会一直是第一张glide缓存的那张图片。我目前的解决办法是：在本地SP里存一个变量来标记每次拍的图片，这样glide缓存的就是不同的图片了，然后在每次APP退出的时候把内存里的本地图片清空
