### ISSUE TITLE
小米的手机蹦机

### ISSUE THREAD

**Issue by 18365759475** [wenchaosong/OCR_identify#6]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=102, result=-1, data=Intent { (has extras) }} to activity {com.ocr/com.ocr.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.baidu.ocr.sdk.model.AccessToken.getAccessToken()' on a null object reference

**Comment by xiaomsh** [comment]
有没有改动代码呀？这是空指针啊，appkey 那些有没有配置对
