### ISSUE TITLE
请问一下，你这个工程和百度ocr官方的demo区别是什么？

### ISSUE THREAD

**Issue by yak99** [wenchaosong/OCR_identify#8]
如题，核心功能基本上和百度的demo一样，请问做了哪些改进？封装了什么？

**Comment by xiaomsh** [comment]
只是把对外的接口封装了，引用后直接调用而已，这难道对比一下看不懂吗？
就是目前没有好用的第三方识别库，我引用一下而已，让大家能解决需求

**Comment by yak99** [comment]
不是我不会对比，只是我说的比较含蓄
